package q1;

import a1.d;
import android.content.Context;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.a7;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.b7;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.bs;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.c7;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.cs;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.d6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.ds;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.e6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.es;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.f6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.fs;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.g6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.gs;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.h6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.hs;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.i6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.is;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.j6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.js;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.k6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.ks;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.l6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.m6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.n6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.o6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.p6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.q6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.r6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.s6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.t6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.u6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.v5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.w6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.x6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y5;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.y6;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z0;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z1;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z2;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z3;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z4;
import com.google.android.gms.internal.mlkit_vision_internal_vkp.z6;
import g3.c;
import j3.a;

public final class j implements d, c {

    /* renamed from: d  reason: collision with root package name */
    public static j f5995d;

    /* renamed from: e  reason: collision with root package name */
    public static final /* synthetic */ j f5996e = new j();

    /* renamed from: f  reason: collision with root package name */
    public static final j f5997f = new j();

    /* renamed from: g  reason: collision with root package name */
    public static final j f5998g = new j();

    /* renamed from: h  reason: collision with root package name */
    public static final /* synthetic */ j f5999h = new j();

    public static synchronized j c() {
        j jVar;
        synchronized (j.class) {
            if (f5995d == null) {
                f5995d = new j();
            }
            jVar = f5995d;
        }
        return jVar;
    }

    public Object a(Object obj) {
        return (byte[]) obj;
    }

    public void b(a aVar) {
        aVar.a(z4.class, v1.f3330a);
        aVar.a(j6.class, k3.f3162a);
        aVar.a(a5.class, w1.f3389a);
        aVar.a(d5.class, y1.f3408a);
        aVar.a(b5.class, x1.f3396a);
        aVar.a(c5.class, z1.f3433a);
        aVar.a(l4.class, e1.f3032a);
        aVar.a(k4.class, d1.f3010a);
        aVar.a(s4.class, o1.f3239a);
        aVar.a(h6.class, e3.f3034a);
        aVar.a(j4.class, c1.f2995a);
        aVar.a(i4.class, b1.f2972a);
        aVar.a(j5.class, h2.f3078a);
        aVar.a(c7.class, k1.f3160a);
        aVar.a(q4.class, m1.f3202a);
        aVar.a(p4.class, j1.f3101a);
        aVar.a(k5.class, i2.f3088a);
        aVar.a(e6.class, b3.f2974a);
        aVar.a(f6.class, c3.f2997a);
        aVar.a(h5.class, f2.f3047a);
        aVar.a(b7.class, l0.f3188a);
        aVar.a(i5.class, g2.f3067a);
        aVar.a(l5.class, j2.f3102a);
        aVar.a(o5.class, m2.f3203a);
        aVar.a(n5.class, l2.f3190a);
        aVar.a(m5.class, k2.f3161a);
        aVar.a(t5.class, r2.f3274a);
        aVar.a(u5.class, s2.f3287a);
        aVar.a(w5.class, u2.f3316a);
        aVar.a(v5.class, t2.f3307a);
        aVar.a(g5.class, e2.f3033a);
        aVar.a(x5.class, v2.f3370a);
        aVar.a(y5.class, w2.f3390a);
        aVar.a(a6.class, x2.f3397a);
        aVar.a(b6.class, y2.f3409a);
        aVar.a(d6.class, z2.f3434a);
        aVar.a(c6.class, a3.f2960a);
        aVar.a(s5.class, n2.f3226a);
        aVar.a(w4.class, t1.f3306a);
        aVar.a(q5.class, p2.f3249a);
        aVar.a(p5.class, o2.f3240a);
        aVar.a(r5.class, q2.f3261a);
        aVar.a(g6.class, d3.f3012a);
        aVar.a(n6.class, o3.f3241a);
        aVar.a(x3.class, q0.f3259a);
        aVar.a(v3.class, o0.f3238a);
        aVar.a(u3.class, n0.f3224a);
        aVar.a(w3.class, p0.f3247a);
        aVar.a(z3.class, s0.f3285a);
        aVar.a(y3.class, r0.f3272a);
        aVar.a(a4.class, t0.f3305a);
        aVar.a(b4.class, u0.f3314a);
        aVar.a(c4.class, v0.f3329a);
        aVar.a(d4.class, w0.f3388a);
        aVar.a(e4.class, x0.f3395a);
        aVar.a(k.class, h0.f3076a);
        aVar.a(m.class, j0.f3100a);
        aVar.a(l.class, i0.f3086a);
        aVar.a(u4.class, r1.f3273a);
        aVar.a(m4.class, f1.f3046a);
        aVar.a(ds.class, o.f3237a);
        aVar.a(cs.class, p.f3246a);
        aVar.a(n4.class, h1.f3077a);
        aVar.a(fs.class, q.f3258a);
        aVar.a(es.class, r.f3271a);
        aVar.a(js.class, u.f3313a);
        aVar.a(is.class, v.f3328a);
        aVar.a(hs.class, s.f3284a);
        aVar.a(gs.class, t.f3304a);
        aVar.a(b.class, w.f3387a);
        aVar.a(ks.class, x.f3394a);
        aVar.a(com.google.android.gms.internal.mlkit_vision_internal_vkp.d.class, y.f3406a);
        aVar.a(com.google.android.gms.internal.mlkit_vision_internal_vkp.c.class, z.f3431a);
        aVar.a(com.google.android.gms.internal.mlkit_vision_internal_vkp.j.class, f0.f3045a);
        aVar.a(i.class, g0.f3065a);
        aVar.a(f.class, a0.f2957a);
        aVar.a(e.class, c0.f2994a);
        aVar.a(h.class, d0.f3009a);
        aVar.a(g.class, e0.f3031a);
        aVar.a(w6.class, h3.f3079a);
        aVar.a(o6.class, g1.f3066a);
        aVar.a(s6.class, d2.f3011a);
        aVar.a(r6.class, c2.f2996a);
        aVar.a(p6.class, l1.f3189a);
        aVar.a(u6.class, g3.f3068a);
        aVar.a(t6.class, f3.f3048a);
        aVar.a(x6.class, i3.f3089a);
        aVar.a(q6.class, p1.f3248a);
        aVar.a(a7.class, q3.f3262a);
        aVar.a(z6.class, r3.f3275a);
        aVar.a(y6.class, p3.f3250a);
        aVar.a(i6.class, j3.f3103a);
        aVar.a(t4.class, q1.f3260a);
        aVar.a(x4.class, u1.f3315a);
        aVar.a(t3.class, m0.f3201a);
        aVar.a(r4.class, n1.f3225a);
        aVar.a(v4.class, s1.f3286a);
        aVar.a(o4.class, i1.f3087a);
        aVar.a(f5.class, b2.f2973a);
        aVar.a(e5.class, a2.f2959a);
        aVar.a(bs.class, n.f3216a);
        aVar.a(k6.class, l3.f3191a);
        aVar.a(m6.class, n3.f3227a);
        aVar.a(l6.class, m3.f3204a);
        aVar.a(s3.class, k0.f3159a);
        aVar.a(h4.class, a1.f2958a);
        aVar.a(g4.class, z0.f3432a);
        aVar.a(f4.class, y0.f3407a);
    }

    public Object d(g3.u uVar) {
        return new r3.i((Context) uVar.a(Context.class));
    }
}
